name: "Build and test API"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up go
        uses: action/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Checkout to repository
        uses: action/checkout@v2

      - name: Build
        run: go build -v

      - name: Test
        run: go test -v .
